project:
  title: "17682 Iot og embeddede systemer, del 1"
  output-dir: output
  type: website
  
  

website:
  # title: "17682 Iot og embeddede systemer, del 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
  sidebar:
    contents: auto
      # contents: Features
        # - Features/*.qmd
        # - Labs/*.qmd
        # - Resources/*.qmd
    background: gray
  draft-mode: unlinked 
  # drafts:
  #   - ./about.qmd
  #   - /playbook.md
  #   - /readme.md
  

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    lang: da
    



